export {default as Hero} from "./Hero";
export {default as BrowseCatg} from "./BrowseCatg";
export {default as Discover} from "./Discover";
export {default as Footer} from "./Footer";
export {default as HowWork} from "./HowWork";
export {default as Newsletter} from "./Newsletter";
export {default as SpecialOffer} from "./SpecialOffer";
export {default as TopCreator} from "./TopCreator";
export {default as Trending} from "./Trending";
